---
# Group all variables.

# Remote user name
ansible_user: ansible

# Cluster Lab Architecture
# Whether to use centralized SAN architecture or not
centralized_san: false

#######################
# DNS configuration
#######################
# DNS server
dns_server: 192.168.0.22
dns_domain: picluster.k3sspk.tk

############################
# restic backup role variables
############################
# Deactivate clean service. Only enabled in one node
restic_clean_service: false
restic_backups_dirs:
  - path: '/etc'
  - path: '/root'
    exclude:
      - pattern: '.cache'
  - path: '/home/ansible'
    exclude:
      - pattern: '.cache'
      - pattern: '.ansible'
  - path: '/home/oss'
    exclude:
      - pattern: '.cache'
