---
all:
  children:
    control:
      hosts:
        gateway:
          hostname: gatewayk3s
          ansible_host: 192.168.20.67
          ip: 192.168.20.67
          mac: 52:54:00:0e:22:e0
        pimaster:
          hostname: pimaster
          ansible_host: localhost
          ansible_connection: local
          ip: 192.168.20.202
          mac: 10:7b:44:90:49:99
    picluster:
      hosts:
        node1:
          hostname: k3snode1
          ansible_host: 192.168.20.20
          ip: 192.168.20.20
          mac: 52:54:00:41:1a:07
        node2:
          hostname: k3snode2
          ansible_host: 192.168.20.30
          ip: 192.168.20.30
          mac: 52:54:00:54:7f:f3
        node3:
          hostname: node3
          ansible_host: 192.168.20.47
          ip: 192.168.20.47
          mac: 52:54:00:6a:99:fb
        node4:
          hostname: node4
          ansible_host: 192.168.20.86
          ip: 192.168.20.86
          mac: 52:54:00:ee:6a:90
        node5:
          hostname: node5
          ansible_host: 192.168.20.53
          ip: 192.168.20.53
          mac: 52:54:00:57:08:78
    raspberrypi:
      hosts:
        node[1:5]:
        gateway:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node1:
        k3s_worker:
          hosts:
            node[2:5]:
