---
all:
  children:
    control:
      hosts:
        gateway:
          hostname: gateway
          ansible_host: 192.168.20.67
          ip: 192.168.20.67
          mac: 52:54:00:0e:22:e0
        pimaster:
          hostname: pimaster
          ansible_host: localhost
          ansible_connection: local
          ip: 192.168.20.202
          mac: 10:7b:44:90:49:99
    picluster:
      hosts:
        node1:
          hostname: node1
          ansible_host: 192.168.20.20
          ip: 192.168.20.20
          mac: 52:54:00:41:1a:07
        node2:
          hostname: node2
          ansible_host: 192.168.20.30
          ip: 192.168.20.30
          mac: 52:54:00:54:7f:f3
        node3:
          hostname: node3
          ansible_host: 10.0.0.13
          ip: 10.0.0.13
          mac: e4:5f:01:2f:49:05
        node4:
          hostname: node4
          ansible_host: 10.0.0.14
          ip: 10.0.0.14
          mac: e4:5f:01:2f:54:82
        node5:
          hostname: node5
          ansible_host: 10.0.0.15
          ip: 10.0.0.15
          mac: e4:5f:01:d9:ec:5c
    raspberrypi:
      hosts:
        node[1:5]:
        gateway:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node1:
        k3s_worker:
          hosts:
            node[2:5]:
